import { describe, expect, it } from 'vitest';

import {
  generateDeploymentSecrets,
  renderSecretsEnv,
  renderSecretsJson
} from '../../scripts/lib/secrets-generator.mjs';

function createDeterministicRandomBytes() {
  let fillValue = 1;

  return (size: number) => {
    const nextBuffer = Buffer.alloc(size, fillValue);
    fillValue += 1;
    return nextBuffer;
  };
}

describe('secrets generator', () => {
  it('generates url-safe deployment secrets and enables AES write mode', () => {
    const secrets = generateDeploymentSecrets({
      randomBytes: createDeterministicRandomBytes()
    });

    expect(secrets.USE_AES_ENCRYPTION).toBe('true');
    expect(secrets.SESSION_SECRET.length).toBeGreaterThanOrEqual(64);
    expect(secrets.ENCRYPTION_KEY.length).toBeGreaterThanOrEqual(64);
    expect(secrets.ENCRYPTION_SALT.length).toBeGreaterThanOrEqual(43);
    expect(secrets.SESSION_SECRET).not.toMatch(/[+/=]/);
    expect(secrets.ENCRYPTION_KEY).not.toMatch(/[+/=]/);
    expect(secrets.ENCRYPTION_SALT).not.toMatch(/[+/=]/);
    expect(secrets.SESSION_SECRET).not.toBe(secrets.ENCRYPTION_KEY);
  });

  it('renders an env block suitable for deployment variables', () => {
    const output = renderSecretsEnv(
      {
        SESSION_SECRET: 'session-secret',
        ENCRYPTION_KEY: 'encryption-key',
        ENCRYPTION_SALT: 'encryption-salt',
        USE_AES_ENCRYPTION: 'true'
      },
      {
        generatedAt: '2026-03-16T00:00:00.000Z'
      }
    );

    expect(output).toContain('# Generated by npm run secrets:generate');
    expect(output).toContain('SESSION_SECRET=session-secret');
    expect(output).toContain('ENCRYPTION_KEY=encryption-key');
    expect(output).toContain('ENCRYPTION_SALT=encryption-salt');
    expect(output).toContain('USE_AES_ENCRYPTION=true');
  });

  it('renders JSON for automation pipelines', () => {
    const output = renderSecretsJson({
      SESSION_SECRET: 'session-secret',
      ENCRYPTION_KEY: 'encryption-key',
      ENCRYPTION_SALT: 'encryption-salt',
      USE_AES_ENCRYPTION: 'true'
    });

    expect(JSON.parse(output)).toEqual({
      SESSION_SECRET: 'session-secret',
      ENCRYPTION_KEY: 'encryption-key',
      ENCRYPTION_SALT: 'encryption-salt',
      USE_AES_ENCRYPTION: 'true'
    });
  });
});
